'''
Class Id's:
1: Camera
2: particleSquare
3: particleCircle
4: Player
5: Vector

'''
#FOR MULTIPLAYER MAKE SURE EACH PLAYER ID IS DIFFERENT, 1-4


CANVAS_WIDTH = 1300
CANVAS_HEIGHT = 700


#CAMERA
CAM_MOVE_SENSITIVITY=20
CAM_ZOOM_SENSITIVITY=0.02
CAM_MIN_DIST=200

#PARTICLE
PARTICLE_VELOCITY= 300
PARTICLE_RADIUS=20
PARTICLE_MAX_RANGE=2000
#SPRITE
SPRITE_FPS=1/20

#PLAYER
PLAYER_ID=1
PLAYER_RADIUS=40
PLAYER_INITIAL_ANGLE=0
PLAYER_DIMENSIONS_X=50
PLAYER_DIMENSIONS_Y=100
PLAYER_INITIAL_VELOCITY_X=0
PLAYER_INITIAL_VELOCITY_Y=0
PLAYER_INITIAL_POSITION_X=100
PLAYER_INITIAL_POSITION_Y=100
PLAYER_SPRITE='elf_demo'